//! Private AST payload serialization for the JavaScript package wrapper.
use ptdgrp_markdown::ast::link::Link;
use ptdgrp_markdown::ast::text::TextRef;
use ptdgrp_markdown::Document;
use ptdgrp_markdown::MarkdownNode;

/// Writes node payloads in the same pre-order as the private `AstData`
/// topology columns. Tree shape and source spans stay in the typed arrays;
/// this JSON buffer carries only variable-sized node data.
pub(crate) fn node_payloads_to_json(doc: &Document) -> String {
    let mut out = Vec::with_capacity(doc.source().len() * 2 + 256);
    out.push(b'[');
    let mut first = true;
    write_payload_subtree(doc, 0, &mut first, &mut out);
    out.push(b']');
    // SAFETY: all bytes are JSON generated by serde_json or ASCII delimiters.
    unsafe { String::from_utf8_unchecked(out) }
}

fn write_payload_subtree(doc: &Document, id: usize, first: &mut bool, out: &mut Vec<u8>) {
    if !*first {
        out.push(b',');
    }
    *first = false;

    let node = &doc.tree[id];
    out.extend_from_slice(b"{\"id\":");
    if let Some(block_id) = &node.id {
        let _ = serde_json::to_writer(&mut *out, block_id.as_str());
    } else {
        out.extend_from_slice(b"null");
    }
    write_content(doc, &node.body, out);
    out.push(b'}');

    let mut child = doc.tree.get_first_child(id);
    while let Some(child_id) = child {
        write_payload_subtree(doc, child_id, first, out);
        child = doc.tree.get_next(child_id);
    }
}

fn materialize(text: &mut TextRef, source: &str) {
    if matches!(text, TextRef::Source(_)) {
        *text = TextRef::Owned(text.resolve(source).to_string());
    }
}

fn write_content(doc: &Document, body: &MarkdownNode, out: &mut Vec<u8>) {
    match body {
        // TextRef 载荷：物化后写出（Text 直接借 resolved 字符串，零克隆）
        MarkdownNode::Text(t) => {
            out.extend_from_slice(b",\"content\":");
            let _ = serde_json::to_writer(&mut *out, doc.text(t));
        }
        MarkdownNode::Link(link) => {
            let mut link = link.clone();
            if let Link::Default(d) = link.as_mut() {
                materialize(&mut d.url, doc.source());
                if let Some(title) = &mut d.title {
                    materialize(title, doc.source());
                }
            }
            out.extend_from_slice(b",\"content\":");
            let _ = serde_json::to_writer(&mut *out, &*link);
        }
        MarkdownNode::Image(image) => {
            let mut image = image.clone();
            materialize(&mut image.url, doc.source());
            if let Some(title) = &mut image.title {
                materialize(title, doc.source());
            }
            out.extend_from_slice(b",\"content\":");
            let _ = serde_json::to_writer(&mut *out, &*image);
        }
        // 无载荷的结构性节点：省略 content
        MarkdownNode::Document
        | MarkdownNode::Paragraph
        | MarkdownNode::SoftBreak
        | MarkdownNode::HardBreak
        | MarkdownNode::Strong
        | MarkdownNode::Emphasis
        | MarkdownNode::BlockQuote
        | MarkdownNode::ThematicBreak
        | MarkdownNode::Strikethrough
        | MarkdownNode::Highlighting
        | MarkdownNode::FootnoteList
        | MarkdownNode::TableHead
        | MarkdownNode::TableBody
        | MarkdownNode::TableRow
        | MarkdownNode::TableHeadCol
        | MarkdownNode::TableDataCol => {}
        // 其余载荷：untagged serde 与 `.tree` 同形
        other => {
            out.extend_from_slice(b",\"content\":");
            let _ = serde_json::to_writer(&mut *out, other);
        }
    }
}
